# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad_actual', models.TextField()),
                ('doctor_enfermera', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
                ('examen_fisico', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('hecho', models.BooleanField(default=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.Historia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuncionesVitales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('imc', models.IntegerField()),
                ('masa_corporal', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('presion_arterial', models.IntegerField()),
                ('talla', models.IntegerField()),
                ('temperatura', models.IntegerField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.Consulta')),
            ],
        ),
    ]
