# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedadactual', models.CharField(max_length=60)),
                ('examenfisico', models.CharField(max_length=60)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('suministrar', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'permissions': (('list_consulta', 'Can list consulta'), ('get_consulta', 'Can get consulta')),
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'permissions': (('list_diagnostico', 'Can list diagnostico'), ('get_diagnostico', 'Can get diagnostico')),
                'verbose_name_plural': 'Diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='EspecificacionReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('dosis', models.IntegerField()),
                ('periodo', models.CharField(max_length=20)),
                ('recomendacion', models.TextField(blank=True, null=True)),
                ('importe', models.FloatField(blank=True, null=True)),
                ('precio_venta', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EspecificacionReceta',
                'permissions': (('list_especificacionreceta', 'Can list especificacionreceta'), ('get_especificacionreceta', 'Can get especificacionreceta')),
                'verbose_name_plural': 'EspecificacionRecetas',
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('atencion', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historia',
                'permissions': (('list_historia', 'Can list historia'), ('get_historia', 'Can get historia')),
                'verbose_name_plural': 'Historias',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('preciocompra', models.FloatField()),
                ('stock', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('PASTILLA', 'pastilla'), ('INYECTABLE', 'inyectable'), ('JARABE', 'jarabe'), ('VITAMINA', 'vitamina'), ('OTRO', 'otro')], default='PASTILLA', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'permissions': (('list_medicamento', 'Can list medicamento'), ('get_medicamento', 'Can get medicamento')),
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('periododescanso', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('citafecha', models.DateTimeField(blank=True, null=True)),
                ('aministracion', models.BooleanField(default=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='topico2.Consulta')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'permissions': (('list_tratamiento', 'Can list tratamiento'), ('get_tratamiento', 'Can get tratamiento')),
                'verbose_name_plural': 'Tratamientos',
            },
        ),
        migrations.AddField(
            model_name='especificacionreceta',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico2.Medicamento'),
        ),
        migrations.AddField(
            model_name='especificacionreceta',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico2.Tratamiento'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico',
            field=models.ManyToManyField(blank=True, to='topico2.Diagnostico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico2.Historia'),
        ),
    ]
